name: Soroban Smart Contracts CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
      - name: Install Rust target for Soroban
        run: |
          source $HOME/.cargo/env
          rustup target add wasm32v1-none
      - name: Install Stellar CLI with Homebrew
        run: |
          brew update
          brew install stellar-cli
          stellar --version
      - name: Build Cargo project
        run: |
          source $HOME/.cargo/env
          cargo build --verbose

      - name: Build Soroban contract
        run: |
          source $HOME/.cargo/env
          stellar contract build --verbose

      - name: Run Cargo tests
        run: |
          source $HOME/.cargo/env
          cargo test --verbose
        